[build-system]
requires = ["setuptools>=45.0", "wheel", "PyOpenSSL==20.0.1", "pycryptodome==3.15.0", "cffi==1.14.6"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88

[tox]
isolated_build = true
